### ISSUE TITLE
wxml-to-canvas组件适配的问题

### ISSUE THREAD

**Issue by yzbaoo** [wechat-miniprogram/wxml-to-canvas#1]
需求：
下载海报，每张海报都是wxml和wxss写的，所以想转成canvas，在下载。
问题：
在用的过程中发现，如果想下载，必须先画在页面上，但是画在页面上的wxml-to-canvas宽高不能动态设置，设置之后canvas的宽高都变成了0px，无法达到自适应。
尝试过画到页面中，但是将其隐藏：
```
<view style="display:none">
  <wxml-to-canvas/>
</view>
```
但是执行到`canvasToTempFilePath()`卡住了，没有任何报错信息，这是为什么呢？

**Comment by yzbaoo** [comment]
position:absolute;
top:-1000px;

**Comment by DengMingHao** [comment]
`
<wxml-to-canvas class="widget" width="{{width}}" height="{{height}}" ></wxml-to-canvas>
`
这样子能设置画布的大小。

**Comment by shinewen189** [comment]
动态设置是有问题  应该生命周期还没获取到值  我在源码加了一个定时器就拿到

**Comment by wechat-miniprogram-admin** [comment]
先创建离屏的 wxml-to-canvas 组件，通过 width 和 height 设置画布大小。
