### ISSUE TITLE
图片创建失败，iPhone 7 plus ,微信版本7.0.20 (in promise) miniprogram error createImage fail wxfile

### ISSUE THREAD

**Issue by beysong** [wechat-miniprogram/wxml-to-canvas#13]
`<image class="img" src="https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=3582589792,4046843010&fm=26&gp=0.jpg"></image>`

![error](https://user-images.githubusercontent.com/5705613/103255442-4aa9ed00-49c4-11eb-9343-1e5b4a3dea20.jpeg)

**Comment by beysong** [comment]
试了几个型号的手机，只有7p报错

**Comment by whatberry** [comment]
遇到跟你一样的问题，iPhone XR，iOS 13.6，基础库2.14.1，微信版本7.0.20

**Comment by Bittenbydog** [comment]
iPhone 6S Plus: `iOS 14.0 WeChat 7.0.15 WeChatLib: 2.13.2` 没有问题
iPhone XS: `iOS 14.2 WeChat 7.0.20 WeChatLib: 1.14.1` 遇到同样问题

**Comment by suguoyao** [comment]
遇到跟你一样的问题，iPhone XR，iOS 14.2，基础库2.14.1，微信版本7.0.20

**Comment by suguoyao** [comment]
https://developers.weixin.qq.com/community/develop/doc/00062ec1f14a98c4937ba91e356400?highLine=wxml-to-canvas
应该是官方的问题，等待修复。

**Comment by ghost** [comment]
微信官方已修复，iOS更新7.0.21版本
