### ISSUE TITLE
请问如何动态传值？

### ISSUE THREAD

**Issue by BEIBEI123** [wechat-miniprogram/wxml-to-canvas#2]
我想绘制一个宣传海报，上面有用户的头像和昵称，因为每个用户的信息都不同，请问应该如何动态传值满足需求？

**Comment by smackgg** [comment]
@BEIBEI123 wxml 文件都是可以动态生成的，可以随便写动态值。可以参考 [参考代码](https://github.com/smack-o/wechat-app-hrbust/blob/v2/src/pages/gradeShare/demo.js)

**Comment by DengMingHao** [comment]
wxml 的字符串模板，用 ${} 进行插值。
