### ISSUE TITLE
画布尺寸问题

### ISSUE THREAD

**Issue by xiaoyaozi1010** [wechat-miniprogram/wxml-to-canvas#4]
查看dom结构发现wxml-to-canvas组件内置的canvas画布尺寸是写死的400*300，那么如果要绘制长图或者其他尺寸的图，则需要等比缩小，太复杂，建议优化

**Comment by DengMingHao** [comment]
<wxml-to-canvas class="widget" width="{{width}}" height="{{height}}" ></wxml-to-canvas>
我看了一下源码，需要这样用才行。

**Comment by xiaoyaozi1010** [comment]
> `<wxml-to-canvas class="widget" width="{{width}}" height="{{height}}" ></wxml-to-canvas>`
> 我看了一下源码，需要这样用才行。

确实如此。
